### ISSUE TITLE
Meta_query args not parsed by sc_object_list

### ISSUE THREAD

**Issue by LemondRinds** [UCF/Main-Site-Theme#1]
*In case anyone would like to track it* in the base.php file, the sc_object_list function will not pass meta_query args to the WP_Query call used to return objects. The args will be caught by the taxonomies var's array_diff initialization and used as part of the tax_query logic.
![image](https://cloud.githubusercontent.com/assets/20599319/19933195/f4cf428c-a0e8-11e6-874f-ad4690551140.png)

I used an ez/dumb fix. If there's another/better way of implementing this functionality I'd love to know.
![image](https://cloud.githubusercontent.com/assets/20599319/19933251/1ecd05d8-a0e9-11e6-8344-b7da84fb22fb.png)

**Comment by cjg89** [comment]
Thanks for pointing this out.  Yes, the logic for pulling out taxonomies from $attrs assumes that the difference between the keys in $attrs and $default_attrs will always be taxonomy references and nothing else--so, because a 'meta_query' key is present in $attrs and not $default_attrs, that array_diff() on line 1078 will pull out 'meta_query' from $attrs into $taxonomies, assuming it is a taxonomy reference.

Haven't tested this, but I think the way to fix this would to:
1) Update $default_attrs on line 1038 to add `'meta_query' => array()`, so that 'meta_query' won't get caught in that array_diff() as an assumed taxonomy term set, and
2) Update $query_array on line 1101 to add `'meta_query' => $params['meta_query']`, so that any passed-in meta_query will actually get passed to WP_Query on line 1111.

**Comment by cjg89** [comment]
We probably won't have a chance to look at implementing/testing a fix for this right away, but I've put it on our list of things to do.  But if the fix in my previous comment works for you, feel free to submit a pull request and we'll take a look as soon as we can.  Thanks!

**Comment by jmbarne3** [comment]
Going to close out this issue as this functionality is being removed from v3 of the theme. I believe the functionality exists in similar form through a number of plugins we support, and are much more feature rich when it comes to filtering down my meta or taxonomy.
